### ISSUE TITLE
Convert to JSON

### ISSUE THREAD

**Issue by WesWrench** [clokep/mwcomposerfromhell#6]
Hello,

thank you for your release 0.5. I will test it more in depth in order to give you my feedback.

Would it be possible to convert the wikipedia "navboxes" (table at the bottom of the page) into a "JSON" model (dictionary of dictionary in order to manage tables where line can contain several "sub-lines") : 
![image](https://user-images.githubusercontent.com/31844088/209475761-f9be793c-fb87-4dcd-beda-995495ade84f.png)

Best regards,

**Comment by clokep** [comment]
> Would it be possible to convert the wikipedia "navboxes" (table at the bottom of the page) into a "JSON" model (dictionary of dictionary in order to manage tables where line can contain several "sub-lines") :

This seems quite out of scope for `mwcomposerfromhell`. I suspect you could fairly easily do this using just `mwparserfromhell` and some simple scripting.
